absolute-paths-allowed-crates = [
    "color_eyre",
    "clap",
    "crate",
    "hashbrown",
    "tokio",
    "tokio_util",
    "tracing",
    "tracing_subscriber",
    "std",
    "quick_xml",
    "xml",
]

disallowed-macros = [
    { path = "std::assert_ne", reason = "use `pretty_assertions::assert_ne` instead" },
    { path = "std::assert_eq", reason = "use `pretty_assertions::assert_eq` instead" },
    # https://doc.rust-lang.org/std/assert_matches/macro.assert_matches.html
    # { path = "std::assert_matches", reason = "use `pretty_assertions::assert_matches` instead" },
]
