allowed-duplicate-crates = [
    "base64",
    "getrandom",
    "hashbrown",
    "indexmap",
    "regex-automata",
    "regex-syntax",
    "tower",
    "wasi",
    "windows-sys",
    "zerocopy",
    "zerocopy-derive",
]
